name: compile

on:
  schedule:
    - cron: "*/3 * * * *"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  getdata:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: install deps
        run: |
          pip install requests
      - name: execute python script
        run: |
          python compile.py
        working-directory: scripts
      - name: commit changes
        run: |
          git config user.email "annafdowell@gmail.com"
          git config user.name "Anna Dowell"
          git add test3.csv
          git commit -m 'newData'
          git push
