name: compile

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  getdata:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: install deps
        run: |
          pip install pandas

      - name: execute python script
        run: |
          python scripts/compile.py

      - name: commit changes
        run: |
          git config user.email "annadowell@gmail.com"
          git config user.name "Anna Dowell"
          git add CompiledMps.csv
          git add CompiledInterests.csv
          git add CompiledQuestions.csv
          git commit -m 'newData'
          git push
